{% set name = "refet" %}
{% set version = "0.4.1" %}
{% set sha256 = "7ea2bedbb6cfd48837a485162777ab146d98b6a68ee10d72b0871eab773ba891" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - refet

about:
  home: https://github.com/WSWUP/RefET
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: ASCE Standardized Reference Evapotranspiration Functions

extra:
  recipe-maintainers:
    - cgmorton
