{% set name = "refet" %}
{% set version = "0.3.10" %}
{% set sha256 = "2f2f558fc8c1ed62462a434bdf542fb8081ea69c7c216ff7c3214457a14e9c4d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - numpy

test:
  imports:
    - refet

about:
  home: https://github.com/DRI-WSWUP/RefET
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: 'ASCE Standardized Reference Evapotranspiration Functions'

extra:
  recipe-maintainers:
    - cgmorton
