travis:
  secure:
    BINSTAR_TOKEN: b2uhfX8DnvoVeA+agBjOwx9ukx4RJhsasN81WACZfY5FA4REWh8hIpMUrCWNS2oNDUu/AwgpdUhTI79zWS1NM24ddNvcPXefT8Ts9b25LPAjKdvtWGyo2Bf7M2EFapXGvFzsUB6TOpW601oqUCdbkou5nPs0Kf42bKoejzcvEVSPLN7Dhg9XfDwgF0kmQRQIphbyHBkd0I3bXznbJuf0Gr3a3h12mN5D9Y/uyA5zako+kjDC+kGGWJgp89K8CQMz0d/6xgEjqJ7e80VD9wWK3+SiWmgNzaD6lsCz3GqZLpUBdiiE/w5sOqTqSCIYhvjaGQ8Dh+bYlKBnh5vXpe0WckbR9pElw6IbNz0Q1bIpf9/KgH+UBEWT+8HQbCldYfTvApuH2Rph+82d6+yr9JBCxW5Z+ixEbkpbp7E4ZMRCQa73btd/YI2V9wM/GbV8ps/dbMDvQFDGRCjc+qV2gSj/ZRguNYvp2M4JPVfFeheQU4POWV59XtqJFdUQnhmbIlSpwNJW3yPrmL/rnnAPA3KtndNybP4rFg8EVRznUQ5TcUbU+IU27yRAEBGlYwoUdul7w+dQEQyJnXS2N9wIJlkwbZf1IKBA99plYd/VkL1Dgr+v1RDBM5HBvAWHVPoj/ZTTPWWXLqA8awAQ8U2ZvIwTJyw9t5H+Mx8VaFgNDI/K3wU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
